# Generated by Django 4.1.7 on 2023-03-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="is_admin",),
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("Admin", "Admin")],
                default="Regular",
                max_length=7,
            ),
        ),
    ]
